# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
   # Our Phoenix container.
   phoenix:
      # The build parameters for this container.
      build: 
         dockerfile: ./Dockerfile
         context: .
      restart: always
      volumes:
         - ./app:/app
         - ./app/priv/authorized_keys/authorized_keys:/home/uploader_t_1/.ssh/authorized_keys
      env_file: .env
      ports:
         # Mapping the port to make the Phoenix app accessible outside of the container.
         - 4001:4001
         - 7000:7000
         - "3022:22"
      depends_on:
         # The DB container needs to be started before we start this container.
         - db

   db:
      # We use the predefined Postgres image.
      image: postgres:9.6
      env_file: .env
      environment:
         # Set a path where Postgres should store the data.
         pgdata: /var/lib/postgresql/data/pgdata
      restart: always
      volumes:
         - pgdata:/var/lib/postgresql/data
      # ports:
      #    - 5433:5432
# Define the volumes
volumes:
  pgdata:
    external: false
