version: '3'
services:
    mosquitto:
        container_name: MQTT-Container
        build: .
        restart: always
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./data:/mosquitto/data
            - ./log:/mosquitto/log
